home/urls.py
from django.urls import path

urlpatterns = [

]

projetovev/urls.py
from django.contrib import admin
from django.urls import path, include
urlpatterns = [
    path('', include('home.urls')),
    path('admin/', admin.site.urls),
    path('', include('despesas.urls'))
]

despesas/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
class Categoria(models.Model):
    nome = models.CharField(max_length=120)
    descricao = models.TextField(blank = True,null= True)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome

class Despesa(models.Model):
    nome = models.CharField(max_length=100)
    descricao = models.TextField(blank=True, null=True)
    data = models.DateField()
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome

    def clean(self):
        if self.valor < 0:
            raise ValidationError('O valor da despesa não pode ser negativo.')

class Deposito(models.Model):
    usuario = models.ForeignKey(User, on_delete=models.CASCADE)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    valor = models.DecimalField(max_digits=10, decimal_places=2)
    data = models.DateField()
    descricao = models.CharField(max_length=255, blank=True, null=True)

    def __str__(self):
        return f'{self.descricao} - {self.valor:.2f}'

    def clean(self):
        if self.valor < 0:
            raise ValidationError('O valor do depósito não pode ser negativo.')

templates/categorias/editar_categoria.html
{% extends 'base.html' %}
{% load bootstrap %}

{% block content %}
<div>
    <h2>Editar Categoria</h2>
    <div class="col-md-8">
        <form action="" method="post">
            {% csrf_token %}
            {{ form|bootstrap }}
            <button class="btn btn-primary mt-2" type="submit">Atualizar Categoria</button>
        </form>
    </div>
</div>
{% endblock %}

templates/categorias/excluir_categoria.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h2 class="mt-4">Excluir Categoria</h2>
    <div class="alert alert-warning">
        <p><strong>Atenção!</strong> Esta ação não pode ser desfeita.</p>
    </div>

    <p>Tem certeza que deseja excluir a categoria "<strong>{{ categoria.nome }}</strong>"?</p>

    <form method="POST">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger" onclick="return confirm('Tem certeza que deseja excluir esta categoria?');">Confirmar</button>
        <a href="{% url 'gerenciar_categorias' %}" class="btn btn-secondary">Cancelar</a>
    </form>
</div>
{% endblock %}

templates/categorias/gerenciar_categorias.html
{% extends 'base.html' %}
{% load bootstrap %}
{% block content %}
<div>
    <div>
        <h2>Lista de Categorias</h2>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>Nome</th>
                    <th>Descrição</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                {% for categoria in categorias %}
                <tr>
                    <td>{{ categoria.nome }}</td>
                    <td>{{ categoria.descricao }}</td>
                    <td>
                        <a href="{% url 'editar_categoria' categoria.pk %}" class="btn btn-warning">
                            <i class="bi bi-pencil-square"></i> Editar
                        </a>
                        <a href="{% url 'excluir_categoria' categoria.pk %}" class="btn btn-danger">
                            <i class="bi bi-file-x-fill"></i> Excluir
                        </a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
    <div class="mt-4 mb-4">
        <h3>Adicionar Nova Categoria</h3>
        <form action="" method="post">
            {% csrf_token %}
            {{ form|bootstrap }}
            <button class="btn btn-success mt-2" type="submit">Adicionar Categoria</button>
        </form>
    </div>
</div>
<script>
    document.addEventListener('DOMContentLoaded', function() {
        let labelDescricao = document.querySelector('label[for="id_descricao"]');
        if (labelDescricao) {
            labelDescricao.textContent = 'Descrição';
        }
    });
</script>

{% endblock %}